### ISSUE TITLE
Error while launching

### ISSUE THREAD

**Issue by Pepejson** [tellomichmich/PokeNoxBot#1]
I've got following error after I've specified .kml file and named is as Levalois.kml
![image](https://cloud.githubusercontent.com/assets/3199312/17449853/72c5ad74-5b5d-11e6-8bd6-dd8ee28b99e8.png)

**Comment by tellomichmich** [comment]
put a new line before 19.48785

**Comment by Pepejson** [comment]
Ok I got that but now this happens,
![image](https://cloud.githubusercontent.com/assets/3199312/17450548/2951febe-5b61-11e6-8f35-7eb9c7d35bee.png)

**Comment by Pepejson** [comment]
Actually I just didn't copy .dll files among to adb.exe and that's why. So far everything works issue can be closed.

**Comment by tellomichmich** [comment]
I just commited a patch :)
