### ISSUE TITLE
Don'n Caugh Pokemon

### ISSUE THREAD

**Issue by jacoborequena** [tellomichmich/PokeNoxBot#12]
I have a pokemon near, and dont open figth, only print This place is near a Gym !

**Comment by tellomichmich** [comment]
This can append when lot of lured pokestop or a gym is on screen.
The Pokemon detection algorithm is really poor... sorry !

**Comment by jacoborequena** [comment]
i'm programer, in this moment i work in a System for a friend, when finishing i hope  help :D, I do not know much python, but some help not bad

**Comment by jacoborequena** [comment]
What IDE you Used?

**Comment by jacoborequena** [comment]
Whent open pokemon figth not throw  the pokeball and detected as a gym

**Comment by joshwaaa6663** [comment]
hey guys, it wasnt throwing pokeballs at all, just exiting the battle. It was detecting it as a gym.
I didn't fix it from detecting it as a gym but i got it throwing pokeballs by changing the value to false.

    if bIsPokemonFightOpened == True:  
        #This is a big fail maybe a gym detected as Pokemon
        return None

**Comment by joshwaaa6663** [comment]
hey guys. if anyone else is having that issue where it wont throw pokeballs i fixed it.
i mean i dont know python but i found the value that caused it and changed it to false.
here's the text file
[Test.txt](https://github.com/tellomichmich/PokeNoxBot/files/405966/Test.txt)

**Comment by tellomichmich** [comment]
Working on it.

**Comment by jacoborequena** [comment]
the latest version has a bug pokemon says he sees where there is, and poke stops where there is also no: S

**Comment by jacoborequena** [comment]
![find_pokemon](https://cloud.githubusercontent.com/assets/12448390/17537092/c78263b8-5e67-11e6-8f70-1701aeb27475.png)

My map is always click on the left side, as if sensing a Pokemon or pokestop...

**Comment by tellomichmich** [comment]
can you give me OUT_COLOR ? Thanks

**Comment by jacoborequena** [comment]
![out_color](https://cloud.githubusercontent.com/assets/12448390/17551793/1bfe1c40-5eca-11e6-85ae-e9891689625a.png)

**Comment by jacoborequena** [comment]
The latest version even has the error that detects touch in places like Pokemons and there: D
![out_color](https://cloud.githubusercontent.com/assets/12448390/17568829/766f4156-5f13-11e6-844a-f4dc582eeef1.png)

**Comment by tellomichmich** [comment]
Day or Night ?

**Comment by jacoborequena** [comment]
The two images are of day

**Comment by tellomichmich** [comment]
Should be OK...

**Comment by tellomichmich** [comment]
Beware, the new version, will evolve lot of your Pokemon when TransferLowCPPokemon !

**Comment by tellomichmich** [comment]
Thank you for your reporting !

**Comment by jacoborequena** [comment]
Okas okas, not good'm now using the version of 9/08 because it really last long trying to open the pokemons that does not exist and I also just realized that when the stop is far poke the program closes... A time order so I can help it is well: D

**Comment by jacoborequena** [comment]
![out_color](https://cloud.githubusercontent.com/assets/12448390/17608148/6deff170-5ff8-11e6-801e-75a9277a01cf.png)

Touch where not pokemon or pokestop

**Comment by jacoborequena** [comment]
Sorry it Day

**Comment by tellomichmich** [comment]
Thank's ! Are you North oriented ?

**Comment by tellomichmich** [comment]
You are not up to date ! Those colors are already backlisted !

**Comment by jacoborequena** [comment]
Yes north oriented, and yest I use the Versión Ooops :D

**Comment by tellomichmich** [comment]
Do you start PokeNoxBot.py ?

**Comment by jacoborequena** [comment]
Yes, but the error it cause because cuality in config the nox

**Comment by tellomichmich** [comment]
Does it finally works ?

**Comment by joshwaaa6663** [comment]
am i missing something? 
when i type "tesseract filename.tif filename -l eng pdf"
it says can not open input file filename.tif.
i checked and it doesnt seem to be in the extracted file
