### ISSUE TITLE
Error - Speed Driving Warning

### ISSUE THREAD

**Issue by putuoka** [tellomichmich/PokeNoxBot#15]
The script is stop running when facing this warn popup 

![upload](https://cloud.githubusercontent.com/assets/20880839/17636283/bcd00dd6-610e-11e6-88bb-fb87a1364885.png)

**Comment by tellomichmich** [comment]
Did you change speed value ?

**Comment by jacoborequena** [comment]
I change a 7 and work good :D

**Comment by putuoka** [comment]
where to change speed value ?

**Comment by secretagent101** [comment]
i recommend the following fix:
1 .CRT-F towards "[!] LAST HOPE TO ESCAPE !"
2. Comment out "#Tap(0, 0)" 
3. Add "Tap(236, 536)" after ClosePokestop() --- This is to close the warning message.

#Should look something like this
            print "[!] LAST HOPE TO ESCAPE !"
            #Tap(0, 0)
            ClosePokestop()
            Tap(236, 536)

To putuoka - This should solved your problem.

**Comment by putuoka** [comment]
@secretagent101 does not working. it give me error 
  Tap(236, 536)
    ^
IndentationError: unexpected indent

**Comment by tellomichmich** [comment]
I commited the thing, could you say that this is working ?
