### ISSUE TITLE
Too far Pokestop are opened

### ISSUE THREAD

**Issue by secretagent101** [tellomichmich/PokeNoxBot#16]
Hi Michel,
I was wondering, if we could perform a simple math calculation between pokestop relative to player position. To detect if the pokestop is too far and avoid tapping on it. Essentially, speeding up your bot.

I was thinking if we can count the pokestop based on the player relative position:
# playerX - x coordinates of player
# playerY - y coordinates of player

math.hypot(PokeStopPosition[0] - playerX, PokeStopPosition[1] - playerY)

We can then implement if the distance is not within the threshold, we can avoid tap:
if math.hypot(PokeStopPosition[0] - 227, PokeStopPosition[1] - 482) < 85:
    Tap(PokeStopPosition[0], PokeStopPosition[1])

**Comment by tellomichmich** [comment]
Seems verify difficult:
1. We are not precise on pokestop pixel position
2. The plan isn't flat

A better solution is to tweak the eplipse mask to fit the perfect pokestop zone.
