### ISSUE TITLE
Issue during setup

### ISSUE THREAD

**Issue by brak144** [tellomichmich/PokeNoxBot#2]
Forgive me if I'm missing something completely:

-KML was created and renamed Levalois.KML
-adb.exe and AdbWinApi.dll are both in PokeNoxBot directory
-NOX is set to phone, 480x800

Running test.py returns the error @ line 83

SyntaxError: Missing parentheses in call to 'print'

Am I missing something? perhaps a required package for Python as I made a quick and dirty setup on a Win based system and not a Linux system?

**Comment by Pepejson** [comment]
You have python3 installed, you need to have Python 2.7.12 which you can get here https://www.python.org/ftp/python/2.7.12/python-2.7.12.msi

**Comment by brak144** [comment]
Thanks for the info. One more quick question, as PIL has been unmaintained for a while and since I am on a Windows box, would you suggest getting PILLOW repository or what? Currently it's kicking back the error that the PIL module is missing.

**Comment by tellomichmich** [comment]
Ooops, I forgot to talk about Pillow .... 
https://pypi.python.org/pypi/Pillow/3.3.0

Sorry...

**Comment by Pepejson** [comment]
@tellomichmich actually you can also install it using cmd "pip install Pillow"

**Comment by brak144** [comment]
Ok, installed Pillow, updated registry because 32bit and 64 bit don't get along these days. PIL issued solved. Now onto the next issue.

DLL load failed: %1 is not a valid Win32 application.

**Comment by brak144** [comment]
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    from PIL import Image
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 67, in <module>
    from PIL import _imaging as core
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by brak144** [comment]
Ok nvm, scratch that. Didn't have PIP property routed in the PATH within windows system settings

**Comment by threekilos** [comment]
mine is just waiting for pokemon fight .. over and over and over

**Comment by tellomichmich** [comment]
@threekilos you have to modify the variable bIsDay

**Comment by tellomichmich** [comment]
@threekilos or coding a function which detect day or night.

**Comment by brak144** [comment]
I had the same lat/log issue before, but then noticed you patched the script. What change was made for that closed issue?

I also had the same waiting for pokemon issue but the blsDay variable fixed it 100%

**Comment by threekilos** [comment]
so i just change it from False to True?

**Comment by brak144** [comment]
Yeah that's what I did and it worked. The only issue I've seen since occurred when 2 pokestops were within close proximity of another.

It would use one stop, go back to the map, and then go into the next, but then get stuck in the "waiting for pokemon" loop

**Comment by threekilos** [comment]
Weird, its night time on my pokemon go, i tried with both True and False and got the same thing, think ill just wait until other ppl fix it haha:D

**Comment by brak144** [comment]
One other thing I noticed was it didn't detect a pokemon nearby, however I manuall clicked it to fight, it auto threw and auto caught, but then got stuck on the pokemon's stat window and couldn't close that window to go back to map.

**Comment by brak144** [comment]
It also seems to get stuck waiting for pokemon near gyms, I'm assuming because it is color based it is recognizing the pokemon on the gym as real so it keeps waiting.

**Comment by threekilos** [comment]
Also when it says zoom out, how do i do that in nox?

**Comment by brak144** [comment]
double click and then drag

**Comment by threekilos** [comment]
oh okay got it, thanks

**Comment by threekilos** [comment]
got it to spin the pokestops but nothing coming out, think i got soft banned

**Comment by brak144** [comment]
spin the stop manually 40 times

**Comment by threekilos** [comment]
in the process of it now

**Comment by tellomichmich** [comment]
Readme updated :)
