### ISSUE TITLE
After Capture Pokemon

### ISSUE THREAD

**Issue by jacoborequena** [tellomichmich/PokeNoxBot#23]
Sometimes after capture pokemon stays on the screen of reward (candy, exp, etc.) and you have to touch one accept to continue

**Comment by putuoka** [comment]
confirm. it happen to me too. it stuck in print "[!] Pokemon captured !"

**Comment by tellomichmich** [comment]
What's display on screen ?

**Comment by tellomichmich** [comment]
Maybe the tap on close "success" pop-up failed.

**Comment by tellomichmich** [comment]
Can you give me a screenshot when it happens ?

**Comment by putuoka** [comment]
it's stuck in here. don't know what happening 
![upload](https://cloud.githubusercontent.com/assets/20880839/17676700/3cc205bc-6362-11e6-8fad-0adf7f9e077c.png)

**Comment by putuoka** [comment]
it seem its failed to tap ok button and enter infinite loop to this state

while IsPokemonOpen() == False:
        time.sleep(0.5)
        ClearScreen()

**Comment by tellomichmich** [comment]
Ok, I'm testing a patch :)

**Comment by tellomichmich** [comment]
Committed, waiting for your test to close the issue.

**Comment by tellomichmich** [comment]
Beware, the new version will drop any pokemon bellow CP 500, you can change this behavior by editting the CPLimit variable
