### ISSUE TITLE
KeepList to not transfer some pokemon

### ISSUE THREAD

**Issue by Picardu57** [tellomichmich/PokeNoxBot#27]
Hello,

I had these lines to keep Pokemon who don't want to automatic transfer : 

In global def :
`KeepList = ["Magikarp"]`

And after capture I had that :
`elif PokemonCP < TransferCPLimit and PokemonName not in KeepList :`

Maybe you can had to the official branch :)

**Comment by tellomichmich** [comment]
Committed ! Thank you !
