### ISSUE TITLE
Zoom out at startup

### ISSUE THREAD

**Issue by Picardu57** [tellomichmich/PokeNoxBot#29]
Hello,

Sometime, zoom out at startup does not work.
It take the android top bar (notification).

Second case, If PoGo is already lauched, the bot does not make the correct zoom out.

**Comment by Bolo30** [comment]
Hi,
I find a workaround to zoom out every time.
The application sometimes use : 
sendevent /dev/input/event7
or
sendevent /dev/input/event8
or
sendevent /dev/input/event9

so i merged all the possibility in one zoomout.txt file.

[Zoomout.txt](https://github.com/tellomichmich/PokeNoxBot/files/427921/Zoomout.txt)

**Comment by Picardu57** [comment]
Zoom out sometime does not work for me, I need to zoom out manually.
Do you have and idea?

**Comment by tellomichmich** [comment]
Never append to me... I really don't know ! I will make some test

**Comment by tellomichmich** [comment]
When it fails, are you on the map ?

**Comment by Picardu57** [comment]
Yes I'm on. I just update to the last version and reset my nox config, and it's the same thing. At startup, instead of zoom out, the android top bar is "light" openned : 
<img width="242" alt="capture" src="https://cloud.githubusercontent.com/assets/21087728/17831906/c04ea308-66f6-11e6-8354-cf87c7dce2f1.PNG">

**Comment by Picardu57** [comment]
It's work this the Zoomfile.txt bolo30 response. 

It's not the same file (more lauched events) that the current branch.

👍

**Comment by tellomichmich** [comment]
Ok, I will wait some time and some review for @Picardu57  to commit the new Zoomout.txt

**Comment by gabi92a** [comment]
Yes the zoomout don't work, and and when I capture a poquemon, calculate iv crash the bot. When I return from vacation I will help improve the bot.

**Comment by gabi92a** [comment]
#53

**Comment by gabi92a** [comment]
#54 Correctly fixed now.
