### ISSUE TITLE
Wait for Pokemon fight... (and more)

### ISSUE THREAD

**Issue by PassiveModding** [tellomichmich/PokeNoxBot#3]
1.The bot constantly gets stuck with an infinite loop
It works for a few seconds, spins 1 or 2 pokestops and then gets stuck with that issue
![11887f9318ae4c3058d6ef2ef8cee6be](https://cloud.githubusercontent.com/assets/20432486/17454744/c3e37678-5be4-11e6-8c3d-4744dbc96dd8.png)

2.The swipes are constant and do not change if the swipe is inaccurate.
def ThrowPokeball():
    #Near 200
    SwipeTime(236, 780, 236, 400, 190)
rather than having this I believe it would be better to recognise the throw distances and check whether the last one was accurate or not
It works for the most part but if you attempt to catch something like a zubat (or anything far away) it will miss 100% of the throws

3.Also upon catching a new pokemon (that has not been registered in the pokedex) the script will freeze with "Waiting return to the map" Loop
![9be0d99debbc680919216632b98a52bb](https://cloud.githubusercontent.com/assets/20432486/17454776/12196c52-5be6-11e6-8107-ae21d84a3e6e.png)

4.Upon starting I am presented with these few lines not sure what they exactly mean however
![7f79a4a13b73ad230b1224cee74d8d25](https://cloud.githubusercontent.com/assets/20432486/17454815/723b2e58-5be7-11e6-840c-957864b35452.png)

5.The script seems to start at a random location along the KML file which would seemingly increase the ban rate if it begins too far away from the location your app is before the bot begins

**Comment by PassiveModding** [comment]
It would be an incredible script otherwise, much love to the developers though

**Comment by PassiveModding** [comment]
oh and one last thing, after the recent code cleaning changes it also misclicks on pokestops and loops with that as well 
![0dc059fc261179a618e041392b4435ea](https://cloud.githubusercontent.com/assets/20432486/17454857/1dd5f74c-5be9-11e6-8a40-2e1c81e0fc5b.png)

**Comment by tellomichmich** [comment]
Day or Night detection is not implemented. You have to change a variable in the code (bIsDay).

**Comment by PassiveModding** [comment]
@tellomichmich this has fixed the issues with movement, thankyou. Cant wait to see chats next for this
