### ISSUE TITLE
[EVO] Use INI file to init global var

### ISSUE THREAD

**Issue by Picardu57** [tellomichmich/PokeNoxBot#30]
Hello,

For the global var like GreatBallCpLimit, Speed, IVLimit... Maybe you can init theses with an external INI file to not reconfigure at every update.

In my Python projects I use this import:
`import ConfigParser`

Init it with that:

> # Fichier Ini de configuration
> 
> self.config = ConfigParser.ConfigParser()
> self.config.read('config.ini')

And after that, I init a var with this type of line:

> self.path_images = self.config.get('photobooth', 'images')
> self.path_thumbs = self.config.get('photobooth', 'thumbs')

And I use a INI file like this:

> [photobooth]
> images = /home/pi/Pictures/Photobooth/HD/
> thumbs = /home/pi/Pictures/Photobooth/SD/
> compteur = 1
> post_traitement = False
> vitesse_animation = 0.5

You can add this in your branch if you want :) What do you think  about ?

Charles.

**Comment by antfuentes87** [comment]
Why not make a Pull Request?

**Comment by tellomichmich** [comment]
I really prefer JSON config file :), This is on the TODO List !

**Comment by tellomichmich** [comment]
Testing a new version with json config file

**Comment by tellomichmich** [comment]
Et voilà !
