### ISSUE TITLE
Loop on stress/launch pokeball but pokemon already caugh

### ISSUE THREAD

**Issue by Bolo30** [tellomichmich/PokeNoxBot#31]
Hi,

Sometimes after a pokemon was caught, the script loop on #STRESS and  "[!] Throwing a pokeball", but on the game we are on the pokemon statistics (after the sucess pop-up).

It is an endless loop and i need to manually kill/launch the script.

**Comment by tellomichmich** [comment]
Is your version up to date ?

**Comment by tellomichmich** [comment]
The bot can't STRESS more than 30 times

**Comment by Bolo30** [comment]
I'm using latest PokeNoxBot.py and PoGo 0.33.
I will make another tests and come back.

**Comment by Bolo30** [comment]
Hi, 
After new test i no longer see the loop when pokemon was caught, sorry i don't undestand !
