### ISSUE TITLE
Cannot launch script since new version "Start of code cleaning"

### ISSUE THREAD

**Issue by Bolo30** [tellomichmich/PokeNoxBot#32]
Hi,

Since version "Start of code cleaning" i cannot launch the script, error message is : 

Traceback (most recent call last):
  File "c:\python27\pokenoxbot.py", line 1123, in <module>
    loop_geo_points = geo_point_from_kml(config['KMLFile'], config['Speed'])
  File "c:\python27\Utils.py", line 56, in geo_point_from_kml
    f = open(kml_filename)
IOError: [Errno 2] No such file or directory: u'Levallois.kml'

The latest version working fine is "Little optim + KMLFile in configuration" : 

https://github.com/tellomichmich/PokeNoxBot/tree/68adf350cbaf3a9fd065cf22ea8e10ecb0cf90b1

**Comment by tellomichmich** [comment]
Rename to kml file to what you want

**Comment by Bolo30** [comment]
Thank you i mistaked the name of map file, all is ok :-)

**Comment by tellomichmich** [comment]
You win a feature to be implemented ! What do you want ?
