### ISSUE TITLE
Does not correctly detect end of fight and reboot game

### ISSUE THREAD

**Issue by Bolo30** [tellomichmich/PokeNoxBot#34]
Hi,

When pokemon is caugh the script does not correctly detect and reboot game : 

[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[#] Mmmm, something really strange happened !
[+] Looking for pokemon
[!] LAST HOPE TO ESCAPE !
[#] Don't know where we are.... Exiting
[!] Restarting the whole game !

If pokemon flee there is the same behaviour but not enough long to reboot game : 
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[#] Mmmm, something really strange happened !
[+] Looking for pokemon
[+] No more Pokemon not found.

Next to this message the screenshot of game when script bug and does not detect pokemon caugh (then reboot game)

![bug](https://cloud.githubusercontent.com/assets/21132840/17837781/e5482ece-67bc-11e6-8426-67524471aa62.png)

I can see that the "ocr.png" and "ocr.txt" does not update after pokemon caugh, and stay on the value at the begining of the fight (so it's the number of selected pokeball left at the begining).

**Comment by tellomichmich** [comment]
Thank's for you review again ! How many "#STRESS" have you got ?

**Comment by Bolo30** [comment]
Exemple with a pidgey the script just catch : 

[*] Seems to be a Pidgey at 10
[+] 66 Poke Ball left
[+] Throwing a Poke Ball (432)
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[+] #STRESS...
[#] Mmmm, something really strange happened !
[+] Looking for pokemon
[!] LAST HOPE TO ESCAPE !
[#] Don't know where we are.... Exiting
[!] Restarting the whole game !
Events injected: 1

The OUT_FAIL.png : 

![out_fail](https://cloud.githubusercontent.com/assets/21132840/17837958/cd5f43b6-67c0-11e6-897f-e6134cd7a014.png)

Ocr.png : 

![ocr](https://cloud.githubusercontent.com/assets/21132840/17837959/deaa2384-67c0-11e6-8e85-c461246e8bea.png)

**Comment by tellomichmich** [comment]
Ok I understand your bug ! I will try to correct this !

**Comment by Bolo30** [comment]
I tested to modify the line 443 with a value of 40, and it's seem to work !

```
   for i in range(40):
```

**Comment by tellomichmich** [comment]
Yes this a good patch, but the bug append because you have a power full PC. If someone have a more powerfull PC, the bug will append to him.. I going to use time.

**Comment by Bolo30** [comment]
Ok i undestand, thank you for your analysis :-)

**Comment by tellomichmich** [comment]
New version to bugfix your bug :)

**Comment by Bolo30** [comment]
it works like a charm with this new bugfix, you're the boss :-)

**Comment by tellomichmich** [comment]
Don't hesitate to bug report, with your configuration. You should have more bug than this one !
Pokestop opening,
Pokestop spinning,
Pokestop closing,
Pokemon fight opening...
