### ISSUE TITLE
When there is no pokeballs, we must wait 30 "virtual" throwing before script stop fight

### ISSUE THREAD

**Issue by Bolo30** [tellomichmich/PokeNoxBot#35]
It is possible to have script stop fight when he find there is no pokeballs ? (it was the case in past with old release of script)

Thank you  ^^

**Comment by tellomichmich** [comment]
This should be corrected is new version.
`  
        ...

```
    #Check if pokeball are left
    INFO_LOG("%d %s left" % (PokeBallLeft, SelectedPokeball))
    if PokeBallLeft == 0:
        if IsNoMorePokeBall() == True:
            WARNING_LOG("No more pokeball... leaving fight !")
            ClosePokemonFight()
            return None
        PokeBallLeft = GetPokeballLeft()
```

`

**Comment by tellomichmich** [comment]
Can you confirm that it's ok ?

**Comment by Bolo30** [comment]
test in progress :)

**Comment by Bolo30** [comment]
i have the same issue, but what is the modification ? in your first reply i can't find difference between the curent release of script ?!

**Comment by tellomichmich** [comment]
Can you give me log ?

**Comment by tellomichmich** [comment]
Maybe an idea... Can you give me a screenshot when no pokeball happened ?

**Comment by tellomichmich** [comment]
Are you using English Language ?

**Comment by Bolo30** [comment]
my os is in french and i configured nox/android in english
i'm doing screenshot to send you

**Comment by tellomichmich** [comment]
Ok thank's can you give me log too ?

**Comment by Bolo30** [comment]
where can i find other log files ? (other than on screen log)

![2016-08-21_204005](https://cloud.githubusercontent.com/assets/21132840/17839168/9db536fa-67e0-11e6-952f-8d61cdbbfbbc.png)
![2016-08-21_204130](https://cloud.githubusercontent.com/assets/21132840/17839169/9db99a42-67e0-11e6-8cfa-e2732ba9e69e.png)

Actual config in script to check pokeball : 

```
    #Check if pokeball are left
    INFO_LOG("%d %s left" % (PokeBallLeft, SelectedPokeball))
    if PokeBallLeft == 0:
        if IsNoMorePokeBall() == True:
            WARNING_LOG("No more pokeball... leaving fight !")
            ClosePokemonFight()
            return None
        PokeBallLeft = GetPokeballLeft()
```

**Comment by tellomichmich** [comment]
OK, IsNoMorePokeBall seems to fail with you, don't know why...
I committed a workaround for you !
Can you give me the log when this happen again with the new version ?

**Comment by Bolo30** [comment]
ok trying the new version ^^

**Comment by Bolo30** [comment]
It's ok now !

[+] Looking for pokemon
[_] Going to fight with 151 501 !
[+] Wait for Pokemon fight...
[+] Wait for Pokemon fight...
[+] Wait for Pokemon fight...
[@] IsNoMorePokeBall (178,251,165)
[_] Seems to be a Pidgey at 77
[+] 0 Poke Ball left
[@] IsNoMorePokeBall (178,251,165)
[#] No more pokeball... leaving fight !
[#] This place is near a Gym ?
[+] ~10719 Exp/h
[+] Looking around...
[+] Looking for Pokestop
[+] No more Pokestop found.
[+] Looking for pokemon

**Comment by tellomichmich** [comment]
Thank's, the error came from IsNoMorePokeball :)
I committed a patch ! Thanks for all your bug report !

**Comment by tellomichmich** [comment]
Are you on Discord ?

**Comment by Bolo30** [comment]
no but i can come/create an account :)
