### ISSUE TITLE
Automate game restart when communication with server is lost

### ISSUE THREAD

**Issue by Bolo30** [tellomichmich/PokeNoxBot#36]
Hi,

When communication is lost with server, we can see a small pokeball logo spinning (in the top left corner) on the screen.
When this problem occur script does not stop/restart game but no more pokemon spawn and all pokestop are empty.
It is possible to add an automatic restart when this behaviour occur ?

![2016-08-22_101638](https://cloud.githubusercontent.com/assets/21132840/17848082/ef2f259c-6851-11e6-9f7f-b8de22dca810.png)

![2016-08-22_101705](https://cloud.githubusercontent.com/assets/21132840/17848087/f413a4fc-6851-11e6-8024-a09823dee555.png)

**Comment by putuoka** [comment]
you can modify this part in pokenoxbot.py to this one and any others part similar to that
-----------#skip#-------------
clickfailed = 0  
def PokestopWorker(PokeStopPosition):
    global waitingformap
    global clickfailed
    print "[!] Working on Pokestop %d %d" % (PokeStopPosition[0], PokeStopPosition[1])
    Tap(PokeStopPosition[0], PokeStopPosition[1])
    time.sleep(0.6)
    ClearScreen()
    if IsOnMap() == True:
        clickfailed += 1
        print "[!] Click failed ! # %d" % (clickfailed)
        if clickfailed >= 10:
          clickfailed = 0
          RestartApplication()
        return False
    clickfailed = 0
-- next line of code ---

**Comment by tellomichmich** [comment]
I will do that in few hours :)

**Comment by tellomichmich** [comment]
Should be ok ! Waiting for review .

**Comment by Bolo30** [comment]
Ok thank you, test in progress !

**Comment by Bolo30** [comment]
Test done, it's ok now ! script do the restart when game is not correctly connected to server !

Thank you
