### ISSUE TITLE
Sometimes "Clean inventory" does not clean Razz Berry

### ISSUE THREAD

**Issue by Bolo30** [tellomichmich/PokeNoxBot#41]
Hi,

Sometimes script does not drop Razz Berry, altough it is in "config.json" : 
    "ItemToDropList" : ["Potion", "Super Potion", "Hyper Potion", "Revive", "Poke Ball", "Razz Berry", "Great Ball"],

![2016-08-23_133413](https://cloud.githubusercontent.com/assets/21132840/17928253/20676dd2-69fa-11e6-9d37-3e8ca8327276.png)

![2016-08-23_133414](https://cloud.githubusercontent.com/assets/21132840/17928259/261c466c-69fa-11e6-9731-572ed30edc1d.png)

**Comment by tellomichmich** [comment]
This bug is caused by input swipe which is not precise enough... We need to detect first item position by analyzing the screen...

**Comment by Dodo111** [comment]
Probably part of this bug: the bot removed 3x lure modules from my inventory tonight! q_q

**Comment by tellomichmich** [comment]
OK, I will make this bug as maximum priority !

**Comment by tellomichmich** [comment]
I committed a patch. Waiting for your review.

**Comment by Bolo30** [comment]
There is always some mistake with latest script : 

![drop](https://cloud.githubusercontent.com/assets/21132840/18029333/a36042ca-6c95-11e6-863c-b935484c2075.png)

**Comment by tellomichmich** [comment]
"No enough Great Ball to drop" is normal, I don't want to drop great ball under 100. Do you want config for this ?

**Comment by Bolo30** [comment]
I think it's better to only use config.json (and no special customisation).

In my case i have lot of Great Ball and lot of Ultra Ball, so i need to drop Great Ball  :-)

Perhaps only do that with Ultra Ball and not with Great Ball

**Comment by tellomichmich** [comment]
> I  think it's better to only use config.json (and no special customisation).

Sometimes, I don't want to dev during 2 hours just for corner case...

Ok,
 I will change config !

**Comment by tellomichmich** [comment]
I committed a patch ! And you are thanked on Readme for all your reviews !

**Comment by Bolo30** [comment]
Thank you very much, script is now working like a charm ! and great job on config.json we can perfectly customise ressource drop :-)

Closing this issue ^^
