### ISSUE TITLE
Sometimes when game restart, we need to clic "Retry"

### ISSUE THREAD

**Issue by Bolo30** [tellomichmich/PokeNoxBot#42]
Hi,

When game restart, we need sometimes to clic on "Retry" because game say "Failed to log in.", then the game launch.
It will be great if script can to this automatically !

![2016-08-24_212915](https://cloud.githubusercontent.com/assets/21132840/17945000/4045d538-6a42-11e6-8240-b1939f349d03.png)

**Comment by tellomichmich** [comment]
I committed a patch, but It was not tested... because I can't get this error.
Can you tell me if it works ? Thank you !

**Comment by Bolo30** [comment]
Thank you, test in progress, but can be long because this behaviour not happening every time :)

**Comment by Bolo30** [comment]
Script seem to correctly handle "Retry" button now, thank you !
