### ISSUE TITLE
Check Tesseract installation

### ISSUE THREAD

**Issue by Dodo111** [tellomichmich/PokeNoxBot#43]
No pokemon can be caught because the bot isn't detecting pokeballs even though there are over 100:

[+] Wait for Pokemon fight...
[@] IsNoMorePokeBall (255,106,99)
[*] Seems to be a Unknown at 9999
[+] 0 Poke Ball left
[@] IsNoMorePokeBall (165,20,13)
[#] No more pokeball... leaving fight !

Latest version!

**Comment by tellomichmich** [comment]
Are you sur that you correctly installed Tesseract ?

**Comment by Dodo111** [comment]
I do have tesseract extracted to the /bin folder.

I had to manually create a "tmp" directory with a "saved_position.txt" and "ocr.txt" to make the bot work. However it is still not discarding items when the inventory is full.

I'm not sure if these are bugs or I am just missing something (maybe I installed tesseract in the wrong folder?). I realize this isn't a help channel, I've tried joing your discord but the invite expired. Sorry if I am wasting your time :)

PS cool job on the bot :)

**Comment by tellomichmich** [comment]
Did you installed eng.traineddata ?  https://github.com/tesseract-ocr/tessdata

**Comment by Dodo111** [comment]
That's gotta be it then! Thank you :)

PS: there are people on discord trying to sell variants of your bot... just a little heads up. Great work!

**Comment by tellomichmich** [comment]
Commited !
