### ISSUE TITLE
Stuck in Niantic logo while restarting the game

### ISSUE THREAD

**Issue by gabrielfrneto** [tellomichmich/PokeNoxBot#46]
Hello!
Im running your bot in 3 computer now, amazing work!
Sometimes the bot restart the game, and the game stuck in Niantic logo and the bot repeat the "Waiting for map...".
I just edit your code to wait 2 minutes, and if the map not is encountered restart the game again, all was amazing and i could be afk for a long long time.
But sometimes, restart the game not solve the problem, need restart nox! You have any code for your bot restart nox, and then restart game ?
Love your job! MarshallCountz

**Comment by s851151** [comment]
"Retry" and "Sign Out" buttons have the same location. Sometimes I saw my account was signed out. So I  delete tap retry button command. Maybe you got the same sutiation.
Tap(230, 407)

**Comment by gabrielfrneto** [comment]
Not is about signed out.

When the bot restart the game, he do it a lot of times, the game stuck in that white screen with Niantic log, the bot spam "Waiting for map..." forever, my ideia is if the Waiting for map take 2 minutes ,restart game again.

But sometimes restarting the game no solve the problem, need restart the nox, to then restart game.

Have some code to restart nox application?

**Comment by gabi92a** [comment]
#75 Solved
