### ISSUE TITLE
tesseract issue

### ISSUE THREAD

**Issue by joshwaaa6663** [tellomichmich/PokeNoxBot#47]
i followed the instrauctions and everything and it says it cant open filename.tif.
what am i doing wrong?

ever since u started using tesseract i cant get it running. pokenoxbot said something about ocr.png before it crashes

**Comment by suzuke** [comment]
Do u install tesseract-langs-20160524.exe?

**Comment by joshwaaa6663** [comment]
yes i did to the same directory as the core

**Comment by joshwaaa6663** [comment]
so i installed both tesseract-langs-20160524.exe and tesseract-core-20160524.exe to the same directory.
then in command prompt i navigated to it and typed : tesseract filename.tif filename -l eng pdf

it gives me an error: can not open input file filename.tif

i have also searched my computer and there is no sign of filename.tif anywhere.

what am i doing wrong

**Comment by suzuke** [comment]
u have to install both tesseract-langs-20160524.exe and tesseract-core-20160524.exe to the bin directory

**Comment by joshwaaa6663** [comment]
yes

**Comment by joshwaaa6663** [comment]
![Uploading Untitled.jpg…]()

**Comment by joshwaaa6663** [comment]
I did install both of them to the bin directory. 
![untitled](https://cloud.githubusercontent.com/assets/20896707/18038871/2482e86a-6df1-11e6-86d1-4ace996b5dd1.jpg)

**Comment by Lucashamburguru** [comment]
did you ever get it to work? getting the same thing.

**Comment by joshk6656** [comment]
manually create a directory called tmp in the pokenoxbot folder
