### ISSUE TITLE
[#] Don't know where we are.... Exiting

### ISSUE THREAD

**Issue by ardonos** [tellomichmich/PokeNoxBot#49]
[!] LAST HOPE TO ESCAPE !
[#] Don't know where we are.... Exiting
[!] Restarting the whole game !

Whats my mistake?

**Comment by suzuke** [comment]
It is a protection mechanisms that prevents you from getting stuck in certain situation.
Don't worry about it, you did not do anything wrong.

**Comment by ardonos** [comment]
Thanks for answer @suzuke.
