### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by RicardoVaranda** [tellomichmich/PokeNoxBot#5]
Hey mate, Any way to get in contact with you, skype or discord, would love to help you out with making this better.

**Comment by RicardoVaranda** [comment]
Guess I'll give you guys a discord to join if you want to start discussing this:
https://discord.gg/xPm5V

**Comment by jacoborequena** [comment]
Hello, sorry for my bad english, exit for pokemon caugth if no more poke balls

**Comment by tellomichmich** [comment]
In the Readme.md :)
