### ISSUE TITLE
log only send me ## [+] Waiting for map...

### ISSUE THREAD

**Issue by ardonos** [tellomichmich/PokeNoxBot#50]
[+] Waiting for map...
[+] Waiting for map...
[+] Waiting for map...
[+] Waiting for map...
[+] Waiting for map...
[+] Waiting for map...
[+] Waiting for map...
[+] Waiting for map...
[+] Waiting for map...

i use Levalois.kml and already try it with central park. but every time the same problem.

**Comment by ardonos** [comment]
i found its the function RestartApplication beginning on line 697.
its the loop on line 705 -> while IsOnMap() == False:

But i dont know why its not running out of the loop.
Anybody has the same problem or any solution?

**Comment by joshk6656** [comment]
Can you say how you setup Nox from start to finish? Did you enable root? It seems like the image is not being generated for the script to scan.

**Comment by ardonos** [comment]
Hi @joshk6656 thanks for reply.

Normal instance of nox player.
By default root on and set as phone with 480x800.
Just installed some extras like lockito and xposed.

In my /tmp folder from pokenoxbot just a image named "OUT_FAIL.png" with dashboard of phone.

**Comment by joshk6656** [comment]
Do you have teamviewer? I can look if you'd like

**Comment by ardonos** [comment]
first i try a fresh new install from nox :)

**Comment by joshk6656** [comment]
I wouldn't use the nox default installer, I will type up what I did

**Comment by joshk6656** [comment]
Download Nox from here ( http://adf.ly/1cxN5f ). Be careful as its hard to get the download here, I got this URL from the tutorial video.

Install Nox

Install PureAPK. Use PureAPK to update pokemongo.
- Copy C:\Users\USER_NAME\AppData\Roaming\Nox\bin\nox_adb.exe as adb.exe into bin PokeNoxBot directory
- Copy C:\Users\USER_NAME\AppData\Roaming\Nox\bin\AdbWinApi.dll into bin PokeNoxBot directory
- Install http://3.onj.me/tesseract/ into bin PokeNoxBot directory

Then it should work.

**Comment by joshk6656** [comment]
Initially I messed up on these steps. Make sure they are in bin directory

Copy C:\Users\USER_NAME\AppData\Roaming\Nox\bin\nox_adb.exe as adb.exe into **bin** PokeNoxBot directory
Copy C:\Users\USER_NAME\AppData\Roaming\Nox\bin\AdbWinApi.dll into **bin** PokeNoxBot directory

**Comment by ardonos** [comment]
hmm, dont know why... but with the new fresh install it works perfekt :)
