### ISSUE TITLE
Script restart game if fight is in AR Mode

### ISSUE THREAD

**Issue by Bolo30** [tellomichmich/PokeNoxBot#51]
Hi,

If we switch account (for example if we don't want to farm 24/24 with one account), the game automaticaly enbale Augmented Reality Mode when fighting pokemon.
Script does not detect this and restart game. It will be nice if he can detect that and switch AR Mode off :-)

![2016-08-31_000113](https://cloud.githubusercontent.com/assets/21132840/18108798/472bdade-6f0e-11e6-94da-3b946b0043df.png)

**Comment by ardonos** [comment]
Hi, its because no image can create.
If the script start the fight, just deactivate ar or do it manualy before you start the script.
Iam sure in future releases theres a bugfix.

**Comment by joshk6656** [comment]
This is fixed as of 
https://github.com/tellomichmich/PokeNoxBot/commit/e8d9c4b57a2215372f9841f3740c805e97cc09d5

can close this.

**Comment by Bolo30** [comment]
Thank you, bug fixed  :)
