### ISSUE TITLE
line 506     print "[!] Low CP pokemon will be transfered..."]

### ISSUE THREAD

**Issue by biggif89** [tellomichmich/PokeNoxBot#6]
C:\Users\Birkir\Desktop\PokeNoxBot-master>test.py
  File "C:\Users\Birkir\Desktop\PokeNoxBot-master\Test.py", line 506
    print "[!] Low CP pokemon will be transfered..."]
                                                    ^
SyntaxError: invalid syntax

C:\Users\Birkir\Desktop\PokeNoxBot-master>

**Comment by tellomichmich** [comment]
Ooops !
