### ISSUE TITLE
[Request] Write permisions

### ISSUE THREAD

**Issue by gabi92a** [tellomichmich/PokeNoxBot#68]
@tellomichmich Can you give me admin permissions to update this repository ? I'm updating it a lot and there are days that you are not connected.

Greetings and thanks.

**Comment by tellomichmich** [comment]
Mmmm, I was thinking about that but, I'm still waiting you commit a really interesting feature.
And I'm waiting for someone to commit a really interesting features to come back in this project...

**Comment by gabi92a** [comment]
I think this project has future, not right now implement interesting features but solve all the bugs that cause the bot to stop and then I'll get to improve the detection of pokestops that is what most fail. We can work together or keep the project on my side. I will spend many months.

**Comment by tellomichmich** [comment]
I gave you push access...

**Comment by gabi92a** [comment]
Thanks! I 'm looking to implement this method.
http://www.pyimagesearch.com/2015/05/25/basic-motion-detection-and-tracking-with-python-and-opencv/

If it detects a moving object and meets the colors that make tap in the center of the object. I think it will be a good method for detecting pokestops.

**Comment by tellomichmich** [comment]
This is nice ! But Gym will be detect too.... for the moment pokestop detection isn't a problem at all... All Pokestop are detected 100% correctly. The real problem is Pokemon detect... some pokemon aren't detected.

**Comment by tellomichmich** [comment]
Don't hesitate to add your name in Readme.md :)
