### ISSUE TITLE
[Alternative edit .py] catch only pokestops 

### ISSUE THREAD

**Issue by GodZlayer** [tellomichmich/PokeNoxBot#9]
is a simple edit, removing another things... working 

 wrong words but really Works :D

sometimes have bug, but its better if you don't wanna catch pokemons

![screenshot_16](https://cloud.githubusercontent.com/assets/20882230/17460260/6cf2abf4-5c34-11e6-91e3-3a4a7fffaa24.png)
![screenshot_18](https://cloud.githubusercontent.com/assets/20882230/17460261/6cf2ce04-5c34-11e6-9bbd-c8af2dd76a8a.png)

https://gist.github.com/GodZlayer/943277298aa954036742e1d0fd108a75

please make a better, i'm not programmer

**Comment by tellomichmich** [comment]
I Will make argument available when the core is "stabilized".

**Comment by putuoka** [comment]
better to not exclude catch pokemon because stardust is more important than player xp

**Comment by jacoborequena** [comment]
It really is very useful at this time, since the bot detected even when no pokeballs, seeing the code is not difficult to implement the validation if no pokeballs that loops through only about 20 poke stop to recover pokeballs

**Comment by tellomichmich** [comment]
This is the configuration file :)
